[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn movie_backend.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "web"
[[services.ports]]
port = 8000