databases:
  - name: movie-backend-db
    databaseName: movie_backend
    plan: free

redis:
  - name: movie-backend-redis
    plan: free

services:
  - type: web
    name: movie-backend
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn movie_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true