# Generated by Django 5.2.8 on 2025-11-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritemovie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="favoritemovie",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="movies.movie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favoritemovie",
            unique_together={("user", "movie")},
        ),
    ]
